FROM node:18-alpine
WORKDIR /app
COPY . .
ARG NEXT_PUBLIC_AUTH_URL="https://auth.usethread.io"
ENV NEXT_PUBLIC_AUTH_URL=$NEXT_PUBLIC_AUTH_URL
ARG NEXT_PUBLIC_THREAD_AI_URL="https://thread-ai-hhsv6tkqra-uc.a.run.app"
ENV NEXT_PUBLIC_THREAD_AI_URL=$NEXT_PUBLIC_THREAD_AI_URL
# ARG NEXT_PUBLIC_COMPANY="test"
# ENV NEXT_PUBLIC_COMPANY=$NEXT_PUBLIC_COMPANY
ARG PROPELAUTH_REDIRECT_URI=""
ENV PROPELAUTH_REDIRECT_URI=$PROPELAUTH_REDIRECT_URI
ARG PROPELAUTH_API_KEY=""
ENV PROPELAUTH_API_KEY=$PROPELAUTH_API_KEY
RUN npm install --omit=dev
RUN npm run build
CMD ["npm", "start"]