// interface Ingredient {
//   name: string;
//   quantity: number;
//   unit: string;
// }

// interface Recipe {
//   name: string;
//   ingredients: Ingredient[];
// }

// const recipes: Recipe[] = [
//   {
//     name: "Chicken Biryani",
//     ingredients: [
//       { name: "Chicken Thighs", quantity: 750, unit: "g" },
//       { name: "yoghurt", quantity: 150, unit: "ml" },
//       { name: "water", quantity: 125, unit: "ml" },
//       { name: "vegetable oil", quantity: 2, unit: "tbsp" },
//       { name: "garlic cloves", quantity: 6, unit: "" },
//       { name: "grated ginger", quantity: 2, unit: "tsp" },
//       { name: "ground tumeric", quantity: 1 / 8, unit: "tsp" },
//       { name: "cinnamon", quantity: 1 / 4, unit: "tsp" },
//       { name: "cayenne", quantity: 1 / 2, unit: "tsp" },
//       { name: "ground cardamom", quantity: 1 / 2, unit: "tsp" },
//       { name: "garam marsala", quantity: 2, unit: "tsp" },
//       { name: "coriander", quantity: 2, unit: "tsp" },
//       { name: "cumin", quantity: 1, unit: "tbsp" },
//       { name: "paprika", quantity: 2, unit: "tbsp" },
//       { name: "salt", quantity: 1.75, unit: "tsp" },
//       { name: "cloves", quantity: 10, unit: "" },
//       { name: "dried bay leaves", quantity: 5, unit: "" },
//       { name: "star anise", quantity: 1, unit: "" },
//       { name: "green cardamon pods", quantity: 6, unit: "" },
//       { name: "uncooked basmati rice", quantity: 450, unit: "g" },
//       { name: "medium onions", quantity: 2, unit: "" },
//       { name: "oil", quantity: 250, unit: "ml" },
//       { name: "saffron threads", quantity: 1, unit: "tsp" },
//       { name: "coriander or cilantro", quantity: 1, unit: "cup" },
//       { name: "ghee or unsalted butter", quantity: 60, unit: "g" },
//     ],
//   },
//   {
//     name: "Chicken Nihari",
//     ingredients: [
//       { name: "chicken", quantity: 2.2, unit: "lbs" },
//       { name: "ginger paste", quantity: 1, unit: "tbsp" },
//       { name: "garlic paste", quantity: 1, unit: "tbsp" },
//       { name: "fried onions", quantity: 1 / 2, unit: "cup" },
//       { name: "oil", quantity: 1 / 2, unit: "cup" },
//       { name: "water", quantity: 3, unit: "cups" },
//       { name: "bay leaves", quantity: 2, unit: "" },
//       { name: "black pepper", quantity: 1 / 2, unit: "tsp" },
//       { name: "cloves", quantity: 1 / 2, unit: "tsp" },
//       { name: "fennel seeds", quantity: 1 / 2, unit: "tsp" },
//       { name: "black cardamom", quantity: 2, unit: "" },
//       { name: "green cardamom", quantity: 3, unit: "-4" },
//       { name: "cumin seeds", quantity: 1 / 2, unit: "tsp" },
//       { name: "mace", quantity: 0.5, unit: "slice" },
//       { name: "nutmeg", quantity: 0.25, unit: "" },
//       { name: "stick of cinnamon", quantity: 1, unit: "inch" },
//       { name: "star anise", quantity: 1, unit: "" },
//       { name: "salt", quantity: 1.5, unit: "tsp" },
//       { name: "red chili", quantity: 1.5, unit: "tsp" },
//       { name: "Kashmiri chili", quantity: 1, unit: "tsp" },
//       { name: "turmeric", quantity: 1 / 2, unit: "tsp" },
//       { name: "flour whole wheat", quantity: 4, unit: "tbsp" },
//       { name: "water", quantity: 1 / 2, unit: "cup" },
//       { name: "green chilies", quantity: 2, unit: "" },
//       { name: "thinly sliced ginger", quantity: 1, unit: "slice" },
//     ],
//   },
//   {
//     name: "Keema Matar",
//     ingredients: [
//       { name: "neutral oil", quantity: 3, unit: "tbsp" },
//       { name: "cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "medium onion", quantity: 1, unit: "" },
//       { name: "crushed garlic cloves", quantity: 5, unit: "-" },
//       { name: "piece ginger", quantity: 1, unit: "inch" },
//       { name: "ground beef", quantity: 1, unit: "lb" },
//       { name: "ripe tomato", quantity: 250, unit: "g" },
//       { name: "green chili peppers", quantity: 1, unit: "-" },
//       { name: "plain whole-milk yogurt", quantity: 1, unit: "tbsp" },
//       { name: "ground coriander/coriander powder", quantity: 1, unit: "tsp" },
//       { name: "mild red chili powder", quantity: 3 / 4, unit: "tsp" },
//       { name: "turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "kosher salt", quantity: 1 + 1 / 8, unit: "tsp" },
//       { name: "frozen green peas", quantity: 1, unit: "cup" },
//       { name: "small mild green chili pepper", quantity: 1, unit: "" },
//       { name: "freshly ground black pepper", quantity: 1, unit: "tsp" },
//       { name: "garam masala", quantity: (1 / 4 + 1 / 2) / 2, unit: "tsp" },
//       { name: "cilantro leaves", quantity: 1 / 4, unit: "cup" },
//       { name: "fresh lemon or lime juice", quantity: 1 / 2, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Matar Kheema",
//     ingredients: [
//       { name: "neutral oil", quantity: 3, unit: "tbsp" },
//       { name: "cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "medium onion", quantity: 1, unit: "" },
//       { name: "crushed garlic cloves", quantity: 5, unit: "-" },
//       { name: "piece ginger", quantity: 1, unit: "inch" },
//       { name: "ground beef", quantity: 1, unit: "lb" },
//       { name: "ripe tomato", quantity: 250, unit: "g" },
//       { name: "green chili peppers", quantity: 1, unit: "-" },
//       { name: "plain whole-milk yogurt", quantity: 1, unit: "tbsp" },
//       { name: "ground coriander/coriander powder", quantity: 1, unit: "tsp" },
//       { name: "mild red chili powder", quantity: 3 / 4, unit: "tsp" },
//       { name: "turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "kosher salt", quantity: 1 + 1 / 8, unit: "tsp" },
//       { name: "frozen green peas", quantity: 1, unit: "cup" },
//       { name: "small mild green chili pepper", quantity: 1, unit: "" },
//       { name: "freshly ground black pepper", quantity: 1, unit: "tsp" },
//       { name: "garam masala", quantity: (1 / 4 + 1 / 2) / 2, unit: "tsp" },
//       { name: "cilantro leaves", quantity: 1 / 4, unit: "cup" },
//       { name: "fresh lemon or lime juice", quantity: 1 / 2, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Butter Chicken",
//     ingredients: [
//       { name: "plain yoghurt", quantity: 1 / 2, unit: "cup" },
//       { name: "lemon juice", quantity: 1, unit: "tbsp" },
//       { name: "tumeric powder", quantity: 1, unit: "tsp" },
//       { name: "garam masala", quantity: 2, unit: "tsp" },
//       {
//         name: "chili powder or cayenne pepper powder",
//         quantity: 1 / 2,
//         unit: "tsp",
//       },
//       { name: "ground cumin", quantity: 1, unit: "tsp" },
//       { name: "ginger, freshly grated", quantity: 1, unit: "tbsp" },
//       { name: "crushed garlic cloves", quantity: 2, unit: "" },
//       { name: "Chicken thight fillets", quantity: 750, unit: "g" },
//       { name: "ghee or butter", quantity: 2, unit: "tbsp" },
//       { name: "tomato passata/tomato puree", quantity: 1, unit: "cup" },
//       { name: "heavy cream", quantity: 1, unit: "cup" },
//       { name: "sugar", quantity: 1, unit: "tbsp" },
//       { name: "salt", quantity: 1.25, unit: "tsp" },
//       { name: "basmati rice", quantity: 2, unit: "cups" },
//     ],
//   },
//   {
//     name: "Palak Channa Dal",
//     ingredients: [
//       { name: "Chana Dal", quantity: 1, unit: "cup" },
//       { name: "Sliced green chili", quantity: 1, unit: "" },
//       { name: "Grated ginger", quantity: 1, unit: "tbsp" },
//       { name: "Cinnamon stick", quantity: 1, unit: "inch" },
//       { name: "Star anise", quantity: 1, unit: "" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//       { name: "Ghee", quantity: 2, unit: "tbsp" },
//       { name: "Whole dry red chilies", quantity: 2, unit: "" },
//       { name: "Cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "Finely chopped onion", quantity: 1, unit: "cup" },
//       { name: "Finely chopped spinach", quantity: 2, unit: "cups" },
//       { name: "Turmeric powder", quantity: 1, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Chicken Karahi",
//     ingredients: [
//       { name: "Oil", quantity: 1 / 2, unit: "cup" },
//       { name: "Chicken", quantity: 700, unit: "g" },
//       { name: "Finely chopped tomatoes", quantity: 600, unit: "g" },
//       { name: "Minced garlic", quantity: 2.5, unit: "tbsp" },
//       { name: "Minced ginger", quantity: 2, unit: "tbsp" },
//       { name: "Salt", quantity: 1, unit: "tsp" }, // 1-2 tsp, choosing the minimum (1 tsp)
//       { name: "Paprika or Kashmiri red chili", quantity: 2, unit: "tsp" }, // 2 tsp
//       { name: "Crushed black pepper", quantity: 1.5, unit: "tsp" },
//       { name: "Chili flakes", quantity: 1, unit: "tsp" },
//       { name: "Cumin powder", quantity: 0.5, unit: "tsp" },
//       { name: "Coriander powder", quantity: 0.5, unit: "tsp" },
//       { name: "Kalonji", quantity: 1, unit: "tsp" },
//       { name: "Green chillies", quantity: 2, unit: "" }, // 2 green chillies
//       { name: "Coriander", quantity: 0.5, unit: "bunch" },
//       { name: "Cut ginger", quantity: 1 / 4, unit: "cup" },
//     ],
//   },
//   {
//     name: "Chili Chicken",
//     ingredients: [
//       { name: "Boneless chicken", quantity: 250, unit: "g" },
//       { name: "Red chilli sauce", quantity: 1.5, unit: "tsp" },
//       { name: "Soya sauce", quantity: 1.5, unit: "tsp" },
//       { name: "Ground black pepper", quantity: 1 / 4, unit: "tsp" },
//       { name: "Kashmiri red chili powder", quantity: 1 / 4, unit: "tsp" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//       { name: "Cornstarch", quantity: 2, unit: "tbsp" },
//       { name: "All-purpose flour", quantity: 1.5, unit: "tbsp" },
//       { name: "Egg white", quantity: 1, unit: "" },
//       { name: "Oil", quantity: 1 / 4, unit: "cup" },
//       { name: "Soya sauce", quantity: 1, unit: "tbsp" },
//       { name: "Red chilli sauce", quantity: 2, unit: "tbsp" },
//       { name: "Tomato ketchup", quantity: 2, unit: "tbsp" },
//       { name: "Kashmiri red chili powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Ground black pepper", quantity: 1 / 4, unit: "tsp" },
//       { name: "Vinegar", quantity: 3 / 4, unit: "tsp" }, // 3/4-1 tsp, choosing the minimum (3/4 tsp)
//       { name: "Sugar", quantity: 1 / 2, unit: "tsp" }, // 1/2 - 1 tsp, choosing the minimum (1/2 tsp)
//       { name: "Water", quantity: 2, unit: "tbsp" }, // 2-3 tbsp, choosing the minimum (2 tbsp)
//       { name: "Oil", quantity: 1.5, unit: "tbsp" },
//       { name: "Medium onion", quantity: 1, unit: "" },
//       { name: "Fine chopped garlic", quantity: 1, unit: "tbsp" },
//       { name: "Cubed bell pepper", quantity: 1 / 4, unit: "cup" }, // 1/4-1/2 cup, choosing the minimum (1/4 cup)
//       { name: "Green chilies", quantity: 1, unit: "" }, // 1-2 green chilies, choosing the minimum (1 green chili)
//       { name: "Spring onion", quantity: 1, unit: "sprig" },
//       { name: "Spring onion", quantity: 1, unit: "tbsp" }, // 1-3 tbsp spring onion, choosing the minimum (1 tbsp)
//     ],
//   },
//   {
//     name: "Seekh Kabab Roll",
//     ingredients: [
//       { name: "Chicken Keema", quantity: 500, unit: "g" },
//       { name: "Garam Masala", quantity: 1, unit: "tbsp" },
//       { name: "Red Chilli Powder", quantity: 1, unit: "tsp" },
//       { name: "Salt", quantity: 0, unit: "" }, // Salt to taste
//       { name: "Turmeric", quantity: 1 / 2, unit: "tsp" },
//       { name: "Ginger-Garlic Paste", quantity: 1, unit: "tbsp" },
//       { name: "Green Chillies", quantity: 2, unit: "" }, // 2-3 green chilies, choosing the minimum (2 green chilies)
//       { name: "Chopped Cilantro", quantity: 1, unit: "sprig" },
//       { name: "All Purpose Flour", quantity: 1, unit: "cup" },
//       { name: "Water", quantity: 1, unit: "cup" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" }, // Salt to taste
//       { name: "Chopped Onion", quantity: 1, unit: "" },
//     ],
//   },
//   {
//     name: "Chicken Pulao",
//     ingredients: [
//       { name: "Bone-in skinless chicken", quantity: 750, unit: "g" },
//       { name: "Ginger garlic paste", quantity: 1, unit: "tsp" },
//       { name: "Kashmiri Red Chilli Powder", quantity: 1 / 4, unit: "tsp" }, // 1/4 - 1/2 tsp, choosing the minimum (1/4 tsp)
//       { name: "Turmeric", quantity: 1 / 8, unit: "tsp" },
//       { name: "Salt", quantity: 0, unit: "" }, // 1/4 - 1/3 tsp, choosing the minimum (1/4 tsp)
//       { name: "Garam Masala", quantity: 1, unit: "tsp" },
//       { name: "Lemon juice", quantity: 2, unit: "tbsp" },
//       { name: "Bay leaf", quantity: 2, unit: "" },
//       { name: "Star anise", quantity: 2, unit: "" },
//       { name: "Cumin seeds", quantity: 1 / 2, unit: "tsp" }, // 1/2 - 3/4 tsp, choosing the minimum (1/2 tsp)
//       { name: "Garlic cloves", quantity: 6, unit: "" },
//       { name: "Cinnamon (2 inch pieces)", quantity: 2, unit: "pieces" },
//       { name: "Green cardamom", quantity: 8, unit: "" },
//       {
//         name: "Fennel powder or coriander powder",
//         quantity: 3 / 4,
//         unit: "tsp",
//       },
//       { name: "Black cardamom", quantity: 2, unit: "" },
//       { name: "Mace (strand)", quantity: 1, unit: "strand" },
//       { name: "Nutmeg (small)", quantity: 1, unit: "" },
//       { name: "Ghee", quantity: 3, unit: "tbsp" },
//       { name: "Onion (large)", quantity: 1, unit: "" },
//       { name: "Green chilies", quantity: 2, unit: "" }, // 2-3 green chilies, choosing the minimum (2 green chilies)
//       { name: "Tomatoes", quantity: 1 / 3, unit: "" },
//       { name: "Salt", quantity: 3 / 4, unit: "tsp" }, // 1/2 - 3/4 tsp, choosing the minimum (3/4 tsp)
//       { name: "Mint leaves", quantity: 1 / 2, unit: "cup" }, // 1/2 - 3/4 cup, choosing the minimum (1/2 cup)
//       { name: "Coriander leaves", quantity: 1 / 4, unit: "cup" },
//       { name: "Aged basmati rice", quantity: 2, unit: "cups" },
//       { name: "Water", quantity: 3.5, unit: "cups" },
//     ],
//   },
//   {
//     name: "Chicken Tawa Kheema",
//     ingredients: [
//       { name: "Chopped garlic", quantity: 1, unit: "tbsp" },
//       { name: "Chopped ginger", quantity: 1, unit: "tbsp" },
//       { name: "Desi ghee", quantity: 300, unit: "g" },
//       { name: "Green chillies", quantity: 3, unit: "" },
//       { name: "Red chilli (crushed)", quantity: 2, unit: "tsp" },
//       { name: "Kasoori Methi", quantity: 1, unit: "tsp" },
//       { name: "Turmeric powder", quantity: 2, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1, unit: "tsp" },
//       { name: "Fennel seeds (crushed)", quantity: 1, unit: "tsp" },
//       { name: "Mango pickle paste", quantity: 1, unit: "tbsp" },
//       { name: "Salt", quantity: 0, unit: "" },
//       { name: "Onions", quantity: 4, unit: "" },
//       { name: "Spring onions", quantity: 2, unit: "" },
//       { name: "Tomatoes", quantity: 5, unit: "" },
//       { name: "Chicken mince (hand chopped)", quantity: 500, unit: "g" },
//       { name: "Fresh coriander", quantity: 1 / 2, unit: "bunch" },
//     ],
//   },
//   {
//     name: "Chicken Tikka Alfredo",
//     ingredients: [
//       { name: "Boneless skinless chicken thighs", quantity: 1.5, unit: "lb" },
//       { name: "Minced garlic", quantity: 3, unit: "cloves" },
//       { name: "Minced ginger", quantity: 1, unit: "tbsp" },
//       { name: "Ground cumin", quantity: 1, unit: "tsp" },
//       { name: "Ground coriander", quantity: 1, unit: "tsp" },
//       { name: "Large yellow onion (finely chopped)", quantity: 1, unit: "" },
//       { name: "Serrano peppers", quantity: 1, unit: "" },
//       { name: "Can of tomato paste", quantity: 6, unit: "oz" },
//       { name: "Bucatini", quantity: 1, unit: "lb" },
//       { name: "Garam masala", quantity: 2, unit: "tbsp" },
//       { name: "Cayenne", quantity: 1 / 4, unit: "tsp" },
//       { name: "Ground cardamom", quantity: 1, unit: "tsp" },
//       { name: "Honey", quantity: 2, unit: "tsp" },
//       { name: "Full-fat Greek yogurt", quantity: 1 / 2, unit: "cup" },
//       { name: "Ghee or butter", quantity: 3, unit: "tbsp" },
//       { name: "Heavy cream", quantity: 1, unit: "cup" },
//       { name: "Freshly grated Parmesan", quantity: 1 / 4, unit: "cup" },
//       { name: "Kosher salt", quantity: 3 / 4, unit: "tsp" },
//       { name: "Water", quantity: 1.75, unit: "cup" },
//       { name: "Fresh cilantro", quantity: 1, unit: "sprig" },
//       { name: "Cooking spray", quantity: 0, unit: "" },
//     ],
//   },
//   {
//     name: "Chicken 65",
//     ingredients: [
//       { name: "Bone-in chicken", quantity: 600, unit: "g" },
//       { name: "Ginger garlic paste", quantity: 1, unit: "tbsp" },
//       { name: "Salt", quantity: 1 / 3, unit: "tsp" },
//       { name: "Kashmiri red chili powder", quantity: 1.5, unit: "tsp" },
//       { name: "Turmeric", quantity: 1 / 4, unit: "tsp" },
//       { name: "Garam masala", quantity: 1, unit: "tsp" },
//       { name: "Curry leaves", quantity: 6, unit: "sprigs" }, // Total of 6 sprigs, 2 used in marinade, 2 used in tempering, and 2 used for garnish
//       { name: "Curd", quantity: 4, unit: "tbsp" },
//       { name: "Lemon juice", quantity: 1, unit: "tsp" },
//       { name: "Cornstarch", quantity: 4, unit: "tbsp" },
//       { name: "Rice flour", quantity: 2, unit: "tbsp" },
//       { name: "Egg white", quantity: 1, unit: "" },
//       { name: "Oil", quantity: 1.5, unit: "cups" },
//       { name: "Green chilies", quantity: 6, unit: "" },
//       { name: "Chopped garlic", quantity: 1, unit: "tbsp" },
//       { name: "Garlic paste", quantity: 1, unit: "tbsp" },
//       { name: "Sugar", quantity: 1 / 2, unit: "tsp" },
//       { name: "Lemon juice or vinegar", quantity: 1, unit: "tsp" },
//       { name: "Water", quantity: 2, unit: "tbsp" },
//       { name: "Ground black pepper", quantity: 1 / 2, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Chicken Korma",
//     ingredients: [
//       { name: "Bone-in chicken", quantity: 1.2, unit: "lbs" },
//       { name: "Ground turmeric", quantity: 1 / 4, unit: "tsp" },
//       { name: "Curd", quantity: 3, unit: "tbsp" },
//       { name: "Ginger garlic paste", quantity: 1, unit: "tbsp" },
//       { name: "Garam masala", quantity: 3 / 4, unit: "tsp" }, // Ranges from 3/4 to 1 tsp, choosing the minimum (3/4 tsp)
//       { name: "Kashmiri red chilli powder", quantity: 1, unit: "tsp" }, // Ranges from 1 to 1.25 tsp, choosing the minimum (1 tsp)
//       { name: "Salt", quantity: 1 / 2, unit: "tsp" },
//       { name: "Oil or ghee", quantity: 1.5, unit: "tbsp" },
//       { name: "Green cardamoms", quantity: 2, unit: "" },
//       { name: "Sliced onions", quantity: 1, unit: "cup" },
//       { name: "Cashews", quantity: 6, unit: "" },
//       { name: "Almonds", quantity: 4, unit: "" },
//       { name: "Bay leaf", quantity: 1, unit: "small" },
//       { name: "Cloves", quantity: 4, unit: "" },
//       { name: "Cinnamon", quantity: 2, unit: "inch" },
//       { name: "Cardamom", quantity: 1, unit: "" },
//       { name: "Green chilies", quantity: 1, unit: "" }, // 1-2 green chilies, choosing the minimum (1 green chili)
//       { name: "Hot water", quantity: 1 / 2, unit: "cup" }, // 1/2 cup
//       { name: "Garam masala", quantity: 1 / 2, unit: "tsp" }, // Ranges from 1/2 to 3/4 tsp, choosing the minimum (1/2 tsp)
//       { name: "Coriander powder", quantity: 1.5, unit: "tsp" },
//       { name: "Kashmiri red chilli powder", quantity: 1 / 4, unit: "tsp" },
//       { name: "Coriander leaves", quantity: 3, unit: "tbsp" },
//     ],
//   },
//   {
//     name: "Haleem",
//     ingredients: [
//       { name: "Broken wheat", quantity: 1, unit: "cup" },
//       { name: "Boneless mutton, cubed", quantity: 1, unit: "cup" },
//       { name: "Chana dal (split Bengal gram)", quantity: 1 / 2, unit: "cup" },
//       { name: "Masoor dal (red lentils)", quantity: 1 / 4, unit: "cup" },
//       { name: "Moong dal (split green gram)", quantity: 1 / 4, unit: "cup" },
//       { name: "Urad dal (split black gram)", quantity: 1 / 4, unit: "cup" },
//       { name: "Rice", quantity: 1 / 4, unit: "cup" },
//       { name: "Onion, thinly sliced", quantity: 1, unit: "large" },
//       { name: "Ginger-garlic paste", quantity: 2, unit: "tbsp" },
//       { name: "Turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1, unit: "tsp" },
//       { name: "Cooking oil", quantity: 1 / 2, unit: "cup" },
//       { name: "Fresh coriander leaves, chopped", quantity: 1 / 4, unit: "cup" },
//       { name: "Fresh mint leaves, chopped", quantity: 1 / 4, unit: "cup" },
//       { name: "Lemon juice", quantity: 2, unit: "tbsp" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Balti Chicken",
//     ingredients: [
//       { name: "Chicken, cut into pieces", quantity: 500, unit: "g" },
//       { name: "Tomatoes, chopped", quantity: 2, unit: "" },
//       { name: "Onions, thinly sliced", quantity: 2, unit: "" },
//       { name: "Green chilies, sliced", quantity: 2, unit: "" },
//       { name: "Garlic, minced", quantity: 3, unit: "cloves" },
//       { name: "Ginger, grated", quantity: 1, unit: "inch" },
//       { name: "Cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "Coriander seeds", quantity: 1, unit: "tsp" },
//       { name: "Turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Fresh coriander leaves, chopped", quantity: 1 / 4, unit: "cup" },
//       { name: "Cooking oil", quantity: 2, unit: "tbsp" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Peri Peri Chicken",
//     ingredients: [
//       { name: "Chicken thighs or breast pieces", quantity: 4, unit: "" },
//       { name: "Garlic, minced", quantity: 4, unit: "cloves" },
//       { name: "Lemon juice", quantity: 2, unit: "tbsp" },
//       { name: "Olive oil", quantity: 2, unit: "tbsp" },
//       { name: "Paprika", quantity: 1, unit: "tbsp" },
//       { name: "Cayenne pepper", quantity: 1, unit: "tsp" },
//       { name: "Dried oregano", quantity: 1, unit: "tsp" },
//       { name: "Dried thyme", quantity: 1, unit: "tsp" },
//       { name: "Salt", quantity: 1, unit: "tsp" },
//       { name: "Black pepper", quantity: 1 / 2, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Chicken Kofta Curry",
//     ingredients: [
//       { name: "Ground chicken", quantity: 500, unit: "g" },
//       { name: "Onions, finely chopped", quantity: 2, unit: "" },
//       { name: "Garlic, minced", quantity: 3, unit: "cloves" },
//       { name: "Ginger, grated", quantity: 1, unit: "inch" },
//       { name: "Green chilies, finely chopped", quantity: 2, unit: "" },
//       { name: "Fresh coriander leaves, chopped", quantity: 1 / 4, unit: "cup" },
//       { name: "Gram flour (besan)", quantity: 2, unit: "tbsp" },
//       { name: "Cumin powder", quantity: 1, unit: "tsp" },
//       { name: "Coriander powder", quantity: 1, unit: "tsp" },
//       { name: "Turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Yogurt", quantity: 1 / 4, unit: "cup" },
//       { name: "Cooking oil", quantity: 2, unit: "tbsp" },
//       { name: "Tomatoes, chopped", quantity: 2, unit: "" },
//       { name: "Onion, chopped", quantity: 1, unit: "" },
//       { name: "Garlic, minced", quantity: 2, unit: "cloves" },
//       { name: "Ginger, grated", quantity: 1, unit: "inch" },
//       { name: "Cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "Coriander seeds", quantity: 1, unit: "tsp" },
//       { name: "Turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1, unit: "tsp" },
//       { name: "Cooking oil", quantity: 2, unit: "tbsp" },
//       { name: "Fresh coriander leaves, chopped", quantity: 1 / 4, unit: "cup" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Beef Chapli Kebab",
//     ingredients: [
//       { name: "Ground beef", quantity: 500, unit: "g" },
//       { name: "Tomatoes, finely chopped", quantity: 2, unit: "" },
//       { name: "Onions, finely chopped", quantity: 2, unit: "" },
//       { name: "Green chilies, finely chopped", quantity: 2, unit: "" },
//       { name: "Fresh coriander leaves, chopped", quantity: 1 / 4, unit: "cup" },
//       { name: "Pomegranate seeds", quantity: 2, unit: "tbsp" },
//       { name: "Fresh mint leaves, chopped", quantity: 2, unit: "tbsp" },
//       { name: "Ginger, grated", quantity: 2, unit: "tbsp" },
//       { name: "Garlic, minced", quantity: 2, unit: "tbsp" },
//       { name: "Cornflour", quantity: 2, unit: "tbsp" },
//       { name: "Besan (gram flour)", quantity: 2, unit: "tbsp" },
//       { name: "Coriander seeds, crushed", quantity: 2, unit: "tbsp" },
//       { name: "Cumin seeds, crushed", quantity: 2, unit: "tbsp" },
//       { name: "Red chili flakes", quantity: 1, unit: "tbsp" },
//       { name: "Garam masala powder", quantity: 1, unit: "tbsp" },
//       { name: "Salt", quantity: 1, unit: "tsp" },
//       { name: "Cooking oil", quantity: 1 / 2, unit: "cup" },
//     ],
//   },
//   // Repeat the same structure for other recipes
//   {
//     name: "Palak Paneer",
//     ingredients: [
//       {
//         name: "Paneer (Indian cottage cheese), cubed",
//         quantity: 250,
//         unit: "g",
//       },
//       { name: "Spinach (palak), washed and chopped", quantity: 500, unit: "g" },
//       { name: "Onions, chopped", quantity: 2, unit: "" },
//       { name: "Tomatoes, chopped", quantity: 2, unit: "" },
//       { name: "Green chilies", quantity: 2, unit: "" },
//       { name: "Ginger, grated", quantity: 1, unit: "inch" },
//       { name: "Garlic, minced", quantity: 4, unit: "cloves" },
//       { name: "Cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "Coriander powder", quantity: 1, unit: "tsp" },
//       { name: "Turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Fresh cream", quantity: 1 / 4, unit: "cup" },
//       { name: "Cooking oil", quantity: 2, unit: "tbsp" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Bhuna Gosht Chana Dal",
//     ingredients: [
//       { name: "Lamb or beef, cubed", quantity: 500, unit: "g" },
//       { name: "Chana dal (split Bengal gram)", quantity: 1, unit: "cup" },
//       { name: "Onions, finely chopped", quantity: 2, unit: "" },
//       { name: "Tomatoes, chopped", quantity: 3, unit: "" },
//       { name: "Green chilies, chopped", quantity: 2, unit: "" },
//       { name: "Ginger, grated", quantity: 1, unit: "inch" },
//       { name: "Garlic, minced", quantity: 4, unit: "cloves" },
//       { name: "Cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "Coriander powder", quantity: 1, unit: "tsp" },
//       { name: "Turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1, unit: "tsp" },
//       { name: "Fresh coriander leaves, chopped", quantity: 1 / 4, unit: "cup" },
//       { name: "Cooking oil", quantity: 2, unit: "tbsp" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Bhindi Masala",
//     ingredients: [
//       { name: "Okra (Bhindi), washed and chopped", quantity: 500, unit: "g" },
//       { name: "Onions, finely chopped", quantity: 2, unit: "" },
//       { name: "Tomatoes, chopped", quantity: 3, unit: "" },
//       { name: "Green chilies, chopped", quantity: 2, unit: "" },
//       { name: "Ginger, grated", quantity: 1, unit: "inch" },
//       { name: "Garlic, minced", quantity: 4, unit: "cloves" },
//       { name: "Cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "Coriander powder", quantity: 1, unit: "tsp" },
//       { name: "Turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Cooking oil", quantity: 2, unit: "tbsp" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Palak Gosht",
//     ingredients: [
//       { name: "Lamb or beef, cubed", quantity: 500, unit: "g" },
//       { name: "Spinach (palak), washed and chopped", quantity: 500, unit: "g" },
//       { name: "Onions, finely chopped", quantity: 2, unit: "" },
//       { name: "Tomatoes, chopped", quantity: 3, unit: "" },
//       { name: "Green chilies, chopped", quantity: 2, unit: "" },
//       { name: "Ginger, grated", quantity: 1, unit: "inch" },
//       { name: "Garlic, minced", quantity: 4, unit: "cloves" },
//       { name: "Cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "Coriander powder", quantity: 1, unit: "tsp" },
//       { name: "Turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Cooking oil", quantity: 2, unit: "tbsp" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Dal Fry",
//     ingredients: [
//       { name: "Toor dal (split pigeon peas)", quantity: 1, unit: "cup" },
//       { name: "Ghee or oil", quantity: 2, unit: "tbsp" },
//       { name: "Cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "Mustard seeds", quantity: 1, unit: "tsp" },
//       { name: "Green chilies, chopped", quantity: 2, unit: "" },
//       { name: "Ginger, grated", quantity: 1, unit: "inch" },
//       { name: "Garlic, minced", quantity: 4, unit: "cloves" },
//       { name: "Onion, finely chopped", quantity: 1, unit: "" },
//       { name: "Tomatoes, chopped", quantity: 2, unit: "" },
//       { name: "Turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1, unit: "tsp" },
//       { name: "Coriander powder", quantity: 1, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Fresh coriander leaves, chopped", quantity: 2, unit: "tbsp" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Rajma Chawal",
//     ingredients: [
//       {
//         name: "Rajma (red kidney beans), soaked overnight",
//         quantity: 1,
//         unit: "cup",
//       },
//       { name: "Onions, finely chopped", quantity: 2, unit: "" },
//       { name: "Tomatoes, chopped", quantity: 3, unit: "" },
//       { name: "Green chilies, chopped", quantity: 2, unit: "" },
//       { name: "Ginger, grated", quantity: 1, unit: "inch" },
//       { name: "Garlic, minced", quantity: 4, unit: "cloves" },
//       { name: "Ghee or oil", quantity: 2, unit: "tbsp" },
//       { name: "Cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "Coriander powder", quantity: 1, unit: "tsp" },
//       { name: "Turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Fresh coriander leaves, chopped", quantity: 2, unit: "tbsp" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Dal Curry With Rice",
//     ingredients: [
//       { name: "Toor dal (split pigeon peas)", quantity: 1, unit: "cup" },
//       { name: "Tomatoes, chopped", quantity: 2, unit: "" },
//       { name: "Onion, chopped", quantity: 1, unit: "" },
//       { name: "Green chilies, chopped", quantity: 2, unit: "" },
//       { name: "Ginger, grated", quantity: 1, unit: "inch" },
//       { name: "Garlic, minced", quantity: 4, unit: "cloves" },
//       { name: "Mustard seeds", quantity: 1, unit: "tsp" },
//       { name: "Cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "Turmeric powder", quantity: 1, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1, unit: "tsp" },
//       { name: "Coriander powder", quantity: 1, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Cooking oil", quantity: 2, unit: "tbsp" },
//       { name: "Basmati rice", quantity: 1, unit: "cup" },
//       { name: "Water", quantity: 2, unit: "cups" },
//       { name: "Salt", quantity: 1 / 2, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Dal Chole",
//     ingredients: [
//       { name: "Chana dal (split Bengal gram)", quantity: 1, unit: "cup" },
//       { name: "Chickpeas (chana), soaked overnight", quantity: 1, unit: "cup" },
//       { name: "Onions, finely chopped", quantity: 2, unit: "" },
//       { name: "Tomatoes, chopped", quantity: 3, unit: "" },
//       { name: "Green chilies, chopped", quantity: 2, unit: "" },
//       { name: "Ginger, grated", quantity: 1, unit: "inch" },
//       { name: "Garlic, minced", quantity: 4, unit: "cloves" },
//       { name: "Ghee or oil", quantity: 2, unit: "tbsp" },
//       { name: "Cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "Coriander powder", quantity: 1, unit: "tsp" },
//       { name: "Turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1, unit: "tsp" },
//       { name: "Fresh coriander leaves, chopped", quantity: 2, unit: "tbsp" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Chicken Vada Pav",
//     ingredients: [
//       { name: "Ground chicken", quantity: 500, unit: "g" },
//       { name: "Potatoes, boiled and mashed", quantity: 4, unit: "" },
//       { name: "Green chilies, chopped", quantity: 2, unit: "" },
//       { name: "Ginger, grated", quantity: 1, unit: "inch" },
//       { name: "Garlic, minced", quantity: 4, unit: "cloves" },
//       { name: "Cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "Coriander powder", quantity: 1, unit: "tsp" },
//       { name: "Turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Fresh coriander leaves, chopped", quantity: 1 / 4, unit: "cup" },
//       { name: "Bread crumbs", quantity: 1, unit: "cup" },
//       { name: "Eggs, beaten", quantity: 2, unit: "" },
//       { name: "Cooking oil", quantity: 1 / 8, unit: "tsp" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//       { name: "Pav (soft bread rolls)", quantity: 8, unit: "" },
//       { name: "Green chutney", quantity: 1 / 2, unit: "cup" },
//       { name: "Tamarind chutney", quantity: 1 / 2, unit: "cup" },
//       { name: "Butter", quantity: 1 / 8, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Mooli Palak Saag",
//     ingredients: [
//       { name: "Radishes (mooli), grated", quantity: 2, unit: "" },
//       {
//         name: "Spinach (palak), washed and chopped",
//         quantity: 2,
//         unit: "cups",
//       },
//       { name: "Onion, chopped", quantity: 1, unit: "" },
//       { name: "Green chilies, chopped", quantity: 2, unit: "" },
//       { name: "Ginger, grated", quantity: 1, unit: "inch" },
//       { name: "Garlic, minced", quantity: 4, unit: "cloves" },
//       { name: "Cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "Coriander powder", quantity: 1, unit: "tsp" },
//       { name: "Turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Cooking oil", quantity: 2, unit: "tbsp" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Malai Boti Roll",
//     ingredients: [
//       { name: "Boneless chicken, cut into cubes", quantity: 500, unit: "g" },
//       { name: "Yogurt", quantity: 1, unit: "cup" },
//       { name: "Fresh cream", quantity: 1 / 4, unit: "cup" },
//       { name: "Lemon juice", quantity: 2, unit: "tbsp" },
//       { name: "Ginger-garlic paste", quantity: 2, unit: "tbsp" },
//       {
//         name: "Green papaya paste (optional, for tenderizing)",
//         quantity: 1,
//         unit: "tsp",
//       },
//       { name: "Coriander powder", quantity: 1, unit: "tsp" },
//       { name: "Cumin powder", quantity: 1, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "White pepper powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Nutmeg powder", quantity: 1 / 4, unit: "tsp" },
//       { name: "Cardamom powder", quantity: 1 / 4, unit: "tsp" },
//       {
//         name: "Saffron strands, soaked in milk (optional)",
//         quantity: 1 / 4,
//         unit: "tsp",
//       },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//       { name: "Paratha or flatbread", quantity: 4, unit: "" },
//       { name: "Onion, thinly sliced", quantity: 1, unit: "" },
//       { name: "Tomato, thinly sliced", quantity: 1, unit: "" },
//       { name: "Fresh coriander leaves, chopped", quantity: 1 / 4, unit: "cup" },
//       { name: "Green chutney", quantity: 1 / 8, unit: "tsp" },
//       { name: "Tamarind chutney", quantity: 1 / 8, unit: "tsp" },
//       { name: "Mayonnaise", quantity: 1 / 8, unit: "tsp" },
//       { name: "Chat masala", quantity: 1 / 8, unit: "tsp" },
//     ],
//   },
//   {
//     name: "Coconut Chicken Curry",
//     ingredients: [
//       { name: "Boneless chicken, cut into cubes", quantity: 500, unit: "g" },
//       { name: "Coconut milk", quantity: 2, unit: "cups" },
//       { name: "Onion, finely chopped", quantity: 1, unit: "" },
//       { name: "Tomato, chopped", quantity: 2, unit: "" },
//       { name: "Green chilies, chopped", quantity: 2, unit: "" },
//       { name: "Ginger, grated", quantity: 1, unit: "inch" },
//       { name: "Garlic, minced", quantity: 4, unit: "cloves" },
//       { name: "Coriander powder", quantity: 1, unit: "tsp" },
//       { name: "Cumin powder", quantity: 1, unit: "tsp" },
//       { name: "Turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Curry leaves", quantity: 1, unit: "sprig" },
//       { name: "Mustard seeds", quantity: 1, unit: "tsp" },
//       { name: "Cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "Salt", quantity: 1 / 8, unit: "tsp" },
//       { name: "Cooking oil", quantity: 2, unit: "tbsp" },
//       { name: "Fresh coriander leaves, chopped", quantity: 2, unit: "tbsp" },
//     ],
//   },
//   {
//     name: "Matar Gobi",
//     ingredients: [
//       { name: "Cauliflower, cut into florets", quantity: 1, unit: "medium" },
//       { name: "Green peas", quantity: 1, unit: "cup" },
//       { name: "Onion, finely chopped", quantity: 1, unit: "" },
//       { name: "Tomato, chopped", quantity: 2, unit: "" },
//       { name: "Green chilies, chopped", quantity: 2, unit: "" },
//       { name: "Ginger, grated", quantity: 1, unit: "inch" },
//       { name: "Garlic, minced", quantity: 4, unit: "cloves" },
//       { name: "Coriander powder", quantity: 1, unit: "tsp" },
//       { name: "Cumin powder", quantity: 1, unit: "tsp" },
//       { name: "Turmeric powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Red chili powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Garam masala powder", quantity: 1 / 2, unit: "tsp" },
//       { name: "Cumin seeds", quantity: 1, unit: "tsp" },
//       { name: "Salt", quantity: 1 / 2, unit: "tsp" },
//       { name: "Cooking oil", quantity: 2, unit: "tbsp" },
//       { name: "Fresh coriander leaves, chopped", quantity: 2, unit: "tbsp" },
//     ],
//   },
//   {
//     name: "Grilled Chicken Pita",
//     ingredients: [
//       { name: "Boneless chicken breast", quantity: 2, unit: "pieces" },
//       { name: "Pita bread", quantity: 4, unit: "pieces" },
//       { name: "Greek yogurt", quantity: 1 / 2, unit: "cup" },
//       { name: "Lemon juice", quantity: 2, unit: "tbsp" },
//       { name: "Garlic, minced", quantity: 2, unit: "cloves" },
//       { name: "Olive oil", quantity: 2, unit: "tbsp" },
//       { name: "Dried oregano", quantity: 1, unit: "tsp" },
//       { name: "Salt", quantity: 1 / 2, unit: "tsp" },
//       { name: "Black pepper, freshly ground", quantity: 1 / 4, unit: "tsp" },
//       { name: "Lettuce leaves", quantity: 1, unit: "cup" },
//       { name: "Tomato, sliced", quantity: 1, unit: "" },
//       { name: "Red onion, thinly sliced", quantity: 1 / 2, unit: "" },
//       { name: "Cucumber, thinly sliced", quantity: 1 / 2, unit: "" },
//       { name: "Feta cheese, crumbled", quantity: 1 / 2, unit: "cup" },
//       { name: "Fresh parsley, chopped", quantity: 2, unit: "tbsp" },
//       { name: "Lemon wedges", quantity: 4, unit: "" },
//     ],
//   },
// ];

// export function getRecipes() {
//   return recipes;
// }

export function getIngredientsForMeals(
  meals: { mealName: string; count: number }[],
  recipes: any
): { [ingredient: string]: { quantity: number; unit: string } } {
  const ingredientsNeeded: {
    [ingredient: string]: { quantity: number; unit: string };
  } = {};

  meals.forEach(({ mealName, count }) => {
    const meal = recipes.find(
      (recipe: any) => recipe.name.toLowerCase() === mealName.toLowerCase()
    );
    if (!meal) {
      throw new Error(`Meal "${mealName}" not found.`);
    } else {
      meal.ingredients.forEach((ingredient: any) => {
        const totalQuantity = ingredient.quantity * count;
        const ingredientNameLower = ingredient.name.toLowerCase();
        if (ingredientsNeeded[ingredientNameLower]) {
          ingredientsNeeded[ingredientNameLower].quantity += totalQuantity;
        } else {
          ingredientsNeeded[ingredientNameLower] = {
            quantity: totalQuantity,
            unit: ingredient.unit,
          };
        }
      });
    }
  });

  // Sort ingredients alphabetically
  const sortedIngredients: {
    [ingredient: string]: { quantity: number; unit: string };
  } = {};
  Object.keys(ingredientsNeeded)
    .sort((a, b) => a.localeCompare(b))
    .forEach((key) => {
      sortedIngredients[key] = ingredientsNeeded[key];
    });

  return sortedIngredients;
}
